# 测试数据配置文件（初始版本）
# 说明：1. 固定参数直接填写具体值；2. 需随机参数用 {random} 占位；3. 下拉框参数可配置可选值，便于后期扩展
# 业务流程：用户新增（跨3个页面：基本信息页→部门角色页→确认提交页）

# 页面1：用户基本信息页（输入框为主）
user_manage_page_add:
  UserName: "auto_test_user_{random}"  # 动态随机参数（用户名）
  UserName2: "自动化测试_{random}"     # 动态随机参数（真实姓名）
  MobilePhone: "${generate_random_phone_number}"                 # 动态随机参数（手机号，随机4位）
  Password: "${RandomEmail}"   # 动态随机参数（邮箱）
